trainingInput:
  scaleTier: CUSTOM
  masterType: n1-highmem-4
  hyperparameters:
    goal: MAXIMIZE
    hyperparameterMetricTag: mean_val_auc
    maxTrials: 60
    maxParallelTrials: 4
    params:
      - parameterName: gin_bindings=TfExtractor.extractor_fn
        type: CATEGORICAL
        categoricalValues:
        - "@cnn_from_obs"

      - parameterName: gin_bindings=cnn_from_obs.reg_amount
        type: DOUBLE
        minValue: 0.001
        maxValue: 0.2
        scaleType: UNIT_LOG_SCALE
        
      - parameterName: gin_bindings=cnn_from_obs.drop_rate
        type: DOUBLE
        minValue: 0.01
        maxValue: 0.2
        scaleType: UNIT_LOG_SCALE

      - parameterName: gin_bindings=cnn_from_obs.pooling
        type: CATEGORICAL
        categoricalValues:
        - "True"
        - "False"
        
      - parameterName: gin_bindings=cnn_from_obs.conv_layer_params
        type: CATEGORICAL
        categoricalValues:
        - "[[64, 2, 1], [16, 1, 1]]"
        - "[[16, 3, 2], [32, 3, 2]]"