trainingInput:
  scaleTier: CUSTOM
  masterType: n1-highmem-4
  hyperparameters:
    goal: MAXIMIZE
    hyperparameterMetricTag: mean_val_auc
    maxTrials: 60
    maxParallelTrials: 4
    params:

      - parameterName: gin_bindings=AGENT_DIR
        type: CATEGORICAL
        categoricalValues:
        - "'gs://pref_extract_train_output/ppo_search_log_fix_1455626/10/saved_model_cp_8000'"
        - "'gs://pref_extract_train_output/ppo_search_log_fix_1455626/19/saved_model_cp_12000'"
        - "'gs://pref_extract_train_output/search_dqn_40000rb_1365442/39/saved_model_cp_260000'"
        
      - parameterName: gin_bindings=TorchExtractor.num_train
        type: CATEGORICAL
        categoricalValues:
        - "50"
        - "100"
        - "250"
        - "500"
        
      - parameterName: gin_bindings=TorchExtractor.subnet_k
        type: CATEGORICAL
        categoricalValues:
        - "0.001"
        - "0.01"
        - "0.1"
        - "0.25"
        - "0.5"
        - "0.75"

      - parameterName: gin_bindings=TorchExtractor.randomize_weights
        type: CATEGORICAL
        categoricalValues:
        - "True"
        - "False"
        
      - parameterName: gin_bindings=TorchExtractor.learning_rate
        type: DOUBLE
        categoricalValues:
        minValue: 0.001
        maxValue: 0.1
        scaleType: UNIT_LOG_SCALE
