trainingInput:
  scaleTier: CUSTOM
  masterType: n1-standard-4
  hyperparameters:
    goal: MAXIMIZE
    hyperparameterMetricTag: mean_val_auc
    maxTrials: 60
    maxParallelTrials: 5
    params:
      - parameterName: gin_bindings=TorchExtractor.model_fn
        type: CATEGORICAL
        categoricalValues:
        - "@torch_extractor.agent_model"

      - parameterName: gin_bindings=AGENT_DIR
        type: CATEGORICAL
        categoricalValues:
        - "'gs://pref_extract_train_output/ppo_search_log_fix_1455626/10/saved_model_cp_8000'"
        - "'gs://pref_extract_train_output/ppo_search_log_fix_1455626/19/saved_model_cp_12000'"
        - "'gs://pref_extract_train_output/search_dqn_40000rb_1365442/39/saved_model_cp_260000'"
        
      - parameterName: gin_bindings=torch_extractor.agent_model.subnet_k
        type: DOUBLE
        minValue: 0.01
        maxValue: 0.99
        scaleType: UNIT_LINEAR_SCALE
        
      - parameterName: gin_bindings=torch_extractor.agent_model.scores_init
        type: CATEGORICAL
        categoricalValues:
        - "'kaiming_normal'"
        - "'kaiming_uniform'"
        - "'xavier_normal'"
        - "'uniform'"

      - parameterName: gin_bindings=torch_extractor.agent_model.randomize_weights
        type: CATEGORICAL
        categoricalValues:
        - "True"
        - "False"
        
      - parameterName: gin_bindings=TorchExtractor.learning_rate
        type: DOUBLE
        categoricalValues:
        minValue: 0.001
        maxValue: 0.1
        scaleType: UNIT_LOG_SCALE
        
      - parameterName: gin_bindings=TorchExtractor.cosine_anneal_t_max
        type: INTEGER
        minValue: 0
        maxValue: 200
        scaleType: UNIT_LINEAR_SCALE
