trainingInput:
  scaleTier: CUSTOM
  masterType: n1-standard-4
  hyperparameters:
    goal: MAXIMIZE
    hyperparameterMetricTag: mean_val_auc
    maxTrials: 60
    maxParallelTrials: 5
    params:
      - parameterName: gin_bindings=AGENT_DIR
        type: CATEGORICAL
        categoricalValues:
        - "'gs://pref-extr-data/gridworld/saved_model2'"
        
      - parameterName: gin_bindings=DATA_PATH
        type: CATEGORICAL
        categoricalValues:
        - "'gs://pref-extr-data/gridworld/data/train_val_data_1.pkl'"

      - parameterName: gin_bindings=torch_extractor.agent_model.subnet_k
        type: DOUBLE
        minValue: 0.01
        maxValue: 0.99
        scaleType: UNIT_LINEAR_SCALE

      - parameterName: gin_bindings=torch_extractor.agent_model.scores_init
        type: CATEGORICAL
        categoricalValues:
        - "'kaiming_normal'"
        - "'kaiming_uniform'"
        - "'xavier_normal'"
        - "'uniform'"

      - parameterName: gin_bindings=torch_extractor.agent_model.randomize_weights
        type: CATEGORICAL
        categoricalValues:
        - "True"
        - "False"
        
      - parameterName: gin_bindings=TorchExtractor.learning_rate
        type: DOUBLE
        categoricalValues:
        minValue: 0.001
        maxValue: 0.1
        scaleType: UNIT_LOG_SCALE
        
      - parameterName: gin_bindings=TorchExtractor.cosine_anneal_t_max
        type: INTEGER
        minValue: 0
        maxValue: 200
        scaleType: UNIT_LINEAR_SCALE
