trainingInput:
  scaleTier: CUSTOM
  masterType: n1-standard-4
  hyperparameters:
    goal: MAXIMIZE
    hyperparameterMetricTag: mean_val_auc
    maxTrials: 60
    maxParallelTrials: 5
    params:
      - parameterName: gin_bindings=AGENT_DIR
        type: CATEGORICAL
        categoricalValues:
        - "'gs://pref-extr-data/gridworld/simple_env_1/'"

      - parameterName: gin_bindings=TorchExtractor.subnet_k
        type: CATEGORICAL
        categoricalValues:
        - "0.01"
        - "0.1"
        - "0.25"
        - "0.5"
        - "0.75"

      - parameterName: gin_bindings=TorchExtractor.randomize_weights
        type: CATEGORICAL
        categoricalValues:
        - "True"
        - "False"
        
      - parameterName: gin_bindings=TorchExtractor.learning_rate
        type: DOUBLE
        categoricalValues:
        minValue: 0.001
        maxValue: 0.1
        scaleType: UNIT_LOG_SCALE
