trainingInput:
  scaleTier: CUSTOM
  masterType: n1-standard-4
  hyperparameters:
    goal: MAXIMIZE
    hyperparameterMetricTag: mean_val_auc
    maxTrials: 60
    maxParallelTrials: 5
    params:
      - parameterName: gin_bindings=DATA_PATH
        type: CATEGORICAL
        categoricalValues:
        - "'gs://pref-extr-data/gridworld/saved_model2/'"
        
      - parameterName: gin_bindings=AGENT_DIR
        type: CATEGORICAL
        categoricalValues:
        - "'gs://pref-extr-data/gridworld/simple_env_1/'"

      - parameterName: gin_bindings=data_pipeline.from_file
        type: CATEGORICAL
        categoricalValues:
        - "False"

      - parameterName: gin_bindings=data_pipeline.env
        type: CATEGORICAL
        categoricalValues:
        - "Gridworld"

      - parameterName: gin_bindings=agent_extractor.first_size
        type: INTEGER
        minValue: 8
        maxValue: 128
        scaleType: UNIT_LINEAR_SCALE

      - parameterName: gin_bindings=agent_extractor.last_size
        type: INTEGER
        minValue: 4
        maxValue: 32
        scaleType: UNIT_LINEAR_SCALE

      - parameterName: gin_bindings=agent_extractor.num_layers
        type: INTEGER
        minValue: 0
        maxValue: 4
        scaleType: UNIT_LINEAR_SCALE

      - parameterName: gin_bindings=agent_extractor.agent_last_layer
        type: INTEGER
        minValue: 3
        maxValue: 5
        scaleType: UNIT_LINEAR_SCALE
        
      - parameterName: gin_bindings=TfExtractor.slowly_unfreezing
        type: CATEGORICAL
        categoricalValues:
        - "False"

      - parameterName: gin_bindings=agent_extractor.agent_freezed_layers
        type: CATEGORICAL
        categoricalValues:
        - "()"
        - "(0,)"
        - "(0, 1)"
        - "(0, 1, 2)"
        - "(0, 1, 2, 3)"
        
      - parameterName: gin_bindings=SlowlyUnfreezing.start_unfreezing_from
        type: CATEGORICAL
        categoricalValues:
        - "1"
        - "2"
        - "3"
        - "4"
        
      - parameterName: gin_bindings=SlowlyUnfreezing.unfreze_every_n_epochs
        type: INTEGER
        minValue: 5
        maxValue: 100
        scaleType: UNIT_LOG_SCALE

      - parameterName: gin_bindings=agent_extractor.randomize_weights
        type: CATEGORICAL
        categoricalValues:
        - "True"
        - "False"
        
      - parameterName: gin_bindings=agent_extractor.reg_amount
        type: DOUBLE
        minValue: 0.001
        maxValue: 0.2
        scaleType: UNIT_LOG_SCALE
        
      - parameterName: gin_bindings=agent_extractor.drop_rate
        type: DOUBLE
        minValue: 0.01
        maxValue: 0.2
        scaleType: UNIT_LOG_SCALE